### ISSUE TITLE
Merge

### ISSUE THREAD

**Issue by TomWright** [TomWright/dasel#133]
**Is your feature request related to a problem? Please describe.**
It will be good to be able to merge documents on top of eachother.

**Describe the solution you'd like**
Give a single multi selector and have all the results merge into a single document.
`in.json`
```json
{
    "name": "Tom"
}
{
    "age": 27
}
```
```bash
dasel merge -f in.json -o - '.[*]'
```

Result:
```json
{
    "name": "Tom",
    "age": 27
}
```

Dasel should iterate through maps + slices to recursively merge to the deepest level.

**Describe alternatives you've considered**
Ability to provide multiple selectors?

**Comment by pmeier** [comment]
I'd love to have this feature. I often encounter this in CI where I have a base config, but have to adapt it for the specific workflow. If I just need to change one or two things, `dasel put` is reasonable straight forward, but it gets cumbersome quickly. Instead I'd like to do something like `dasel merge -f config.yml -f update.yml`.

I'd prefer to provide `-f` multiple times rather than merging the documents manually into one file. Not saying that shouldn't work as well, but shouldn't be required. 

Also not sure what the selector, e.g. `'.[*]'` from above, should be used for, I'd prefer not specifying anything by default given that `dasel merge` should be reasonably expressive of what is happening.

**Comment by TomWright** [comment]
@pmeier Heard and listened.

In v3 (still in development) this is implemented as:

```
$ cat one.json 
{
  "foo": 1
}

$ cat two.json 
{
  "bar": 2
}

$ daselv3 -o=json one=json:one.json two=json:two.json '{$one..., $two...}'
{"foo":1,"bar":2}
```

What's happening here is that we're setting two variables that can be used in the selector. We're then constructing a new map by spreading both inputs. 

We also have `merge` which will eventually be some form of deep merging functionality, but for now it merges the top level keys:
```
$ daselv3 -o=json one=json:one.json two=json:two.json 'merge($one, $two)'
{"foo":1,"bar":2}
```

The variable definition format isn't final, but it is at least working.

We can also note that this variable usage isn't limited to merge functionality:
```
$ daselv3 -o=json one=json:one.json two=json:two.json '{"1":{"foo":1},"2":{"bar":2},"both":[1,2]}'
{
  "1": {
    "foo": 1
  },
  "2": {
    "bar": 2
  },
  "both": [
    1,
    2
  ]
}
```

I'm pretty excited for these changes!

**Comment by BatmanAoD** [comment]
Won't `...` be a "shallow" merge, overwriting values rather than merging them recursively? That is, I would expect that this:

```sh
echo '{"contents": [1, 2, 3]}' | dasel -i json '
$overload = {
 "contents": [3, 4, 5]
};
{$root..., $overload... }
'
```
... would produce this:

```json
{
 "contents": [3, 4, 5]
}
```

Whereas I want something that would produce this:

```json
{
 "contents": [1, 2, 3, 3, 4, 5]
}
```

(Actually, in my case, the ideal would be to have the duplicate `3` removed, but I'm not sure that makes sense even for a recursive merge.)

I tried to test this with dasel 3.4.1, but got a panic:

```
❯ echo '{"contents": [1, 2, 3]}' | dasel -i json '
$overload = {
 "contents": [3, 4, 5]
};
{$root..., $overload... }
'
panic: runtime error: index out of range [67] with length 67

goroutine 1 [running]:
github.com/tomwright/dasel/v3/selector/lexer.(*Tokenizer).parseCurRune(0x1731bd3bcc68)
        github.com/tomwright/dasel/v3/selector/lexer/tokenize.go:60 +0x2178
github.com/tomwright/dasel/v3/selector/lexer.(*Tokenizer).Next(0x1731bd3bcc68)
        github.com/tomwright/dasel/v3/selector/lexer/tokenize.go:366 +0x44
github.com/tomwright/dasel/v3/selector/lexer.(*Tokenizer).Tokenize(0x1731bd3bcc68)
        github.com/tomwright/dasel/v3/selector/lexer/tokenize.go:27 +0x68
github.com/tomwright/dasel/v3/selector.Parse({0x1731bd55a4b0, 0x43})
        github.com/tomwright/dasel/v3/selector/parser.go:10 +0x48
github.com/tomwright/dasel/v3/execution.ExecuteSelector({0x102dc4c28, 0x102e83dc0}, {0x1731bd55a4b0?, 0x200?}, 0x1731bd5b8330, 0x1731bd4ecac8)
        github.com/tomwright/dasel/v3/execution/execute.go:21 +0x44
github.com/tomwright/dasel/v3/internal/cli.run({0x0, 0x0, 0x0, 0x0, {0x1731bd59c198, 0x4}, {0x1731bd59c198, 0x4}, 0x0, 0x0, ...})
        github.com/tomwright/dasel/v3/internal/cli/run.go:94 +0x6cc
github.com/tomwright/dasel/v3/internal/cli.(*QueryCmd).Run(0x1731bd57c038, 0x1731bd57c000)
        github.com/tomwright/dasel/v3/internal/cli/query.go:55 +0x258
reflect.Value.call({0x102d499a0?, 0x1731bd57c038?, 0x3?}, {0x102988bb4, 0x4}, {0x1731bd3bd7f0, 0x1, 0x1027015a0?})
        reflect/value.go:586 +0xabc
reflect.Value.Call({0x102d499a0?, 0x1731bd57c038?, 0x1731bd3bd878?}, {0x1731bd3bd7f0?, 0x1731bd3bd6e8?, 0x1025ca91c?})
        reflect/value.go:369 +0x94
github.com/alecthomas/kong.callAnyFunction({0x102d499a0?, 0x1731bd57c038?, 0x102d542e0?}, 0x1731bd5b80f0)
        github.com/alecthomas/kong@v1.14.0/callbacks.go:225 +0x6c4
github.com/alecthomas/kong.callFunction({0x102d499a0?, 0x1731bd57c038?, 0x1731bd3bdae0?}, 0x1731bd5b80f0)
        github.com/alecthomas/kong@v1.14.0/callbacks.go:182 +0x1cc
github.com/alecthomas/kong.(*Context).RunNode(0x1731bd4ee600, 0x1731bd5800f0, {0x0, 0x0, 0x0})
        github.com/alecthomas/kong@v1.14.0/context.go:846 +0x664
github.com/alecthomas/kong.(*Context).Run(0x1731bd4ee600, {0x0?, 0x1731bd3bdd38?, 0x7?})
        github.com/alecthomas/kong@v1.14.0/context.go:875 +0x11c
github.com/tomwright/dasel/v3/internal/cli.Run({0x102dc19a8, 0x1731bd482008}, {0x102dc19c8, 0x1731bd482010}, {0x102dc19c8, 0x1731bd482018})
        github.com/tomwright/dasel/v3/internal/cli/command.go:78 +0x480
github.com/tomwright/dasel/v3/internal/cli.MustRun({0x102dc19a8?, 0x1731bd482008?}, {0x102dc19c8?, 0x1731bd482010?}, {0x102dc19c8?, 0x1731bd482018?})
        github.com/tomwright/dasel/v3/internal/cli/command.go:30 +0x38
main.main()
        github.com/tomwright/dasel/v3/cmd/dasel/main.go:24 +0x74
```

**Comment by TomWright** [comment]
I see this is closed, however I have some input.

The error you got is due to the newline at the end of the query, without that we see:
```bash
$ echo '{"contents": [1, 2, 3]}' | dasel -i json '
$overload = {
 "contents": [3, 4, 5]
};
{$root..., $overload... }'
{
    "contents": [
        3,
        4,
        5
} 
```

That said, yes `...` is a shallow merge. I think this is what you'd want:
```bash
$ echo '{"contents": [1, 2, 3]}' | dasel -i json '
$overload = {
 "contents": [3, 4, 5]
};
{"contents": [$root.contents..., $overload.contents...]}'
{
    "contents": [
        1,
        2,
        3,
        3,
        4,
        5
    ]
}
```

Fair point on the duplicate 3. I intend to add a `distinct` func that will remove duplicates or at least someway to nicely incorporate that check into a `filter` call

**Comment by BatmanAoD** [comment]
What I'm really after is a generic "merge toml files" command that doesn't require knowing the keys in advance. 

In the October 2024 comment, you mentioned a deep `merge` operation; is that still planned?

**Comment by pmeier** [comment]
I'd also very much like a deep-merge functionality. Just to add to https://github.com/TomWright/dasel/issues/133#issuecomment-4263841141: I've never encountered a deep-merge functionality that does anything with lists besides replacement, e.g. append, deduplicate, etc. So IMO that would be very unexpected behavior. Deep merge canonically just applies to maps.

**Comment by TomWright** [comment]
This has been released in `v3.7.0`. Thanks for the patience!

```sh
dasel -i json '{{"a": {"x": 1, "y": 2}}..., {"a": {"y": 3, "z": 4}}...}'
{
    "a": {
        "y": 3,
        "z": 4
    }
}
```

**Comment by BatmanAoD** [comment]
Thanks!
