### ISSUE TITLE
Panic when value in TOML is missing

### ISSUE THREAD

**Issue by jaskij** [TomWright/dasel#191]
**Describe the bug**

When a value is entirely missing in TOML dasel panics

**To Reproduce**

Save this as `test.toml`:

```toml
[test]
something =
foo = "bar"
```

And run `dasel -p toml -f test.toml`

**Expected behavior**
A clean error message about malformed TOML

**Stack trace**

<details> <summary>Stack trace collapsed</summary>

```
$ ~/go/bin/dasel -p toml -f test.toml
panic: unhandled token: "foo" [recovered]
	panic: interface conversion: interface {} is *errors.errorString, not string

goroutine 1 [running]:
github.com/pelletier/go-toml.LoadBytes.func1()
	/home/jaskij/go/pkg/mod/github.com/pelletier/go-toml@v1.9.3/toml.go:474 +0xf2
panic({0x99f680, 0xc0002d2010})
	/usr/lib/go/src/runtime/panic.go:1038 +0x215
github.com/pelletier/go-toml.(*tomlParser).parseRvalue(0xc000036cc0)
	/home/jaskij/go/pkg/mod/github.com/pelletier/go-toml@v1.9.3/parser.go:394 +0xd37
github.com/pelletier/go-toml.(*tomlParser).parseAssign(0xc000036cc0)
	/home/jaskij/go/pkg/mod/github.com/pelletier/go-toml@v1.9.3/parser.go:179 +0x112
github.com/pelletier/go-toml.(*tomlParser).run(...)
	/home/jaskij/go/pkg/mod/github.com/pelletier/go-toml@v1.9.3/parser.go:32
github.com/pelletier/go-toml.parseToml({0xc0002c8000, 0x9, 0x100})
	/home/jaskij/go/pkg/mod/github.com/pelletier/go-toml@v1.9.3/parser.go:506 +0x16c
github.com/pelletier/go-toml.LoadBytes({0xc0002c0400, 0xc0002b2960, 0xc000036c01})
	/home/jaskij/go/pkg/mod/github.com/pelletier/go-toml@v1.9.3/toml.go:486 +0x159
github.com/pelletier/go-toml.LoadReader({0xbaed80, 0xc0002b2960})
	/home/jaskij/go/pkg/mod/github.com/pelletier/go-toml@v1.9.3/toml.go:516 +0x45
github.com/pelletier/go-toml.Unmarshal({0xc0002c0200, 0x1f, 0x200}, {0x97b400, 0xc000253ea0})
	/home/jaskij/go/pkg/mod/github.com/pelletier/go-toml@v1.9.3/marshal.go:655 +0xb7
github.com/tomwright/dasel/internal/storage.(*TOMLParser).FromBytes(0xbaf820, {0xc0002c0200, 0x1f, 0x200})
	/home/jaskij/go/pkg/mod/github.com/tomwright/dasel@v1.22.1/internal/storage/toml.go:21 +0x5a
github.com/tomwright/dasel/internal/storage.Load({0xbaf320, 0x1056f80}, {0xbaf820, 0xc0000107a0})
	/home/jaskij/go/pkg/mod/github.com/tomwright/dasel@v1.22.1/internal/storage/parser.go:115 +0x9d
github.com/tomwright/dasel/internal/command.getRootNode({{0x7fff8473e1ce, 0x9}, {0xbaf820, 0xc0000107a0}, {0xbaf320, 0x1056f80}, 0x0}, 0xa11af3)
	/home/jaskij/go/pkg/mod/github.com/tomwright/dasel@v1.22.1/internal/command/put.go:126 +0x1fb
github.com/tomwright/dasel/internal/command.runSelectCommand({{0x7fff8473e1ce, 0x9}, {0x7fff8473e1c6, 0x4}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/home/jaskij/go/pkg/mod/github.com/tomwright/dasel@v1.22.1/internal/command/select.go:93 +0x156
github.com/tomwright/dasel/internal/command.selectCommand.func1(0xc0002b6000, {0xc00025f700, 0x4, 0x4})
	/home/jaskij/go/pkg/mod/github.com/tomwright/dasel@v1.22.1/internal/command/select.go:190 +0x258
github.com/spf13/cobra.(*Command).execute(0xc0002b6000, {0xc00025f6c0, 0x4, 0x4})
	/home/jaskij/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000abb80)
	/home/jaskij/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/jaskij/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/home/jaskij/go/pkg/mod/github.com/tomwright/dasel@v1.22.1/cmd/dasel/main.go:11 +0xb0
```
</details>

**Desktop (please complete the following information):**

<details><summary>Details collapsed</summary>

```
$ inxi -S
System:    Host: ultima-jd-pc Kernel: 5.10.79-1-MANJARO x86_64 bits: 64 Desktop: GNOME 41.1 Distro: Manjaro Linux

$ go version
go version go1.17.3 linux/amd64

$ ~/go/bin/dasel --version
dasel version development-v1.22.1
```
To be precise, Dasel is current master as of writing this (`adf569e9f648e798531415c2589a77b37ffeb668`)

**Additional context**

Giving a cursory look at the stack trace, I'm not entirely sure if the issue is here or upstream in `pelletier/go-toml`, that's why I'm starting here. But I'm not a Go dev.

**Comment by TomWright** [comment]
Thanks for reporting this. I'll take a look asap

**Comment by TomWright** [comment]
This is an upstream issue. I'll open an issue linking to this one.

**Comment by TomWright** [comment]
I've updated the related package and this will be fixed in the next release.
